### ISSUE TITLE
did you git commit a recursive symlink? I think you did.

### ISSUE THREAD

**Issue by itdaniher** [wcc17/TemperatureBar#1]
hey buddy,

I just wanna take a minute to draw attention to something that caught my eye.

https://github.com/wcc17/TemperatureBar/blob/master/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/Temperature/DarkSkyAPIService.m

I laughed.

don't be discouraged, though, as git is a fickle mistress, as are symlinks, as is osx, as is objective c.

edit: remove line number

**Comment by wcc17** [comment]
Looks like I did. I'm pretty lazy with the .gitignore. I'll be fixing that today. How did you find this?

**Comment by itdaniher** [comment]
Searching for darksky sample code, TemperatureBar took up like five pages of the search results XD

**Comment by wcc17** [comment]
thanks for looking out :P

**Comment by itdaniher** [comment]
happy to help. grew up around south ky and posting random side projects to gh, keep hacking!
